# Generated by Django 3.2.9 on 2022-06-11 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_lgtm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_items', to='items.item')),
            ],
        ),
    ]
