# Generated by Django 3.2.9 on 2022-06-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_popularitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularitem',
            name='lgtm_count',
            field=models.IntegerField(default=0),
        ),
    ]
